### ISSUE TITLE
是否考虑使用四个选项的概率大小来评估模型？

### ISSUE THREAD

**Issue by DaoD** [haonan-li/CMMLU#1]
您好，感谢您的工作。

已有的一些工作（包括MMLU和C-Eval等）一般采用比较四个选项生成概率的方法来测试模型的效果，这种方法更适合一些非API访问的基座模型，是否考虑使用这种方法对已有模型进行评估呢？

**Comment by haonan-li** [comment]
你好，为了尽可能消除用正则匹配抽取答案带来的误差，我们目前倾向于输入所有选项内容，然后对比下一个生成词是ABCD的概率。这是也是原本MMLU采用的方式。

**Comment by DaoD** [comment]
OK，现在已经是比较概率了，谢谢！
