### ISSUE TITLE
[Feature] Support CMMLU in OpenCompass

### ISSUE THREAD

**Issue by tonysy** [haonan-li/CMMLU#10]
Hi,
We are the OpenCompass Team.
We sincerely welcome you to contribute the CMMLU dataset into OpenCompass codebase and leaderboard.

Our homepage: https://opencompass.org.cn/
Our codebase: https://github.com/internLM/OpenCompass/

**Comment by isen-zhang** [comment]
Absolutely, we gladly accept the invitation to contribute the CMMLU dataset to OpenCompass' codebase and leaderboard.
