### ISSUE TITLE
[BUG maybe in few-shot setting]计算模型选择的答案时，对于很多模型代码里实际上比较的是['_A', '_B', '_C', '_D']这四个token的概率，而非['A', 'B', 'C', 'D']的概率

### ISSUE THREAD

**Issue by Heepo** [haonan-li/CMMLU#11]
1、在`src/mp_utils.py`中，这段代码`choice_ids = [tokenizer.encode(choice)[-1] for choice in choices]`对于很多tokenizer来说，`choice_ids` 对应的tokens可能并非`['A', 'B', 'C', 'D']`

- llama2-13B tokenizer 执行的结果是
```
>>> choice_ids = [tokenizer.encode(choice)[-1] for choice in choices]
>>> print(choice_ids)
[319, 350, 315, 360]

>>> tokenizer.convert_ids_to_tokens(choice_ids)
['▁A', '▁B', '▁C', '▁D']

>>> tokenizer.convert_tokens_to_ids(['A', 'B', 'C', 'D'])
[29909, 29933, 29907, 29928]
```

- Baichuan-13B tokenizer 执行的结果是
```
>>> choice_ids = [tokenizer.encode(choice)[-1] for choice in choices]
>>> print(choice_ids)
[703, 731, 702, 743]

>>> tokenizer.convert_ids_to_tokens(choice_ids)
['▁A', '▁B', '▁C', '▁D']

>>> tokenizer.convert_tokens_to_ids(['A', 'B', 'C', 'D'])
[31132, 31139, 31133, 31140]
```
**这一实现方式在few-shot场景下可能会是问题**
```
def format_example(df, idx, subject, include_answer=True, cot=False):
    ...
    # Chain-of-thought
    if cot:
        prompt += "\n逐步分析并给出答案选项。"
    else:
        prompt += "\n答案是："

    if include_answer:
        prompt += "{}\n\n".format(df.iloc[idx, k + 1])
```
根据此代码生成的few-shot prompt，以农学12题为例
```
以下是关于农学的单项选择题，请直接给出正确答案的选项。

题目：肉牛屠宰后，胴体的哪个部位肉质较好
A. 胸
B. 腹
C. 大腿
D. 小腿
答案是：C

...

题目：羊胴体中，肉质较好的部位是
A. 胸下肉
B. 肩胛肉
C. 后腿肉
D. 小腿肉
答案是：C

题目：某周的日均温分别为9°C、9°C、11°C、12°C、13°C、15°C、16°C，则对喜温作物(生物学零度为10°C)来说，这周的活动的积温为
A. 67°C
B. 18°C
C. 85°C
D. 17°C
答案是：
```
**注意无论是例题还是最终问题，`答案是：`后面都是没有空格的，也就是说我们期望的模型输出应当是`['A', 'B', 'C', 'D']`4个token之一，而非`['_A', '_B', '_C', '_D']`这4个token之一**。

2、注意到实现方式本身和[MMLU官方代码](https://github.com/hendrycks/test/blob/master/evaluate_flan.py)是一致的
```
>>> flan_tokenizer("A").input_ids
[71, 1]

>>> flan_tokenizer.convert_ids_to_tokens([71, 1])
['▁A', '</s>']
```
但其构造few-shot examples时，**答案前都带有空格**
```
def format_example(df, idx, include_answer=True):
    ...
    prompt += "\nAnswer:"
    if include_answer:
        prompt += " {}\n\n".format(df.iloc[idx, k + 1])
    return prompt
```
**因此预期的模型输出应该为`['_A', '_B', '_C', '_D']`这4个token之一，这里是没有问题的**。

对于zero-shot setting，由于英文通常符号如`:`后都会跟有空格，所以MMLU的题也没问题。但是对于中文使用中文符号`：`，后面通常也不会再跟空格，因为它是全角字符。所以可能也有点问题。

3、对于较鲁棒或者本身较强的LLMs来说，可能`['_A', '_B', '_C', '_D']`和`['A', 'B', 'C', 'D']`概率排序基本是一致的，相对影响较小，但是对于较弱的LLMs可能会有一定影响。
我只测试了Baichuan-13B，修改前后的分数对比如下：
|Subject|对['_A', '_B', '_C', '_D']排序（目前repo的方式）| 对['A', 'B', 'C', 'D']排序|
|-----------| ----------- | ----------- |
|STEM               |42.38  |41.96       |
|Humanities      |61.61   |60.29       |
|Social Science|60.44  |59.32    |
|Other               |59.26   |58.91        |
|China specific | 56.62  |56.3       |
|Avg                   |55.82   |55.01        |

### Possible Solution1
最简单的解决方法，肯定是像MMLU那样在构造example 答案时在选项标号前加上空格，但这样其实不够显式，特别是对于不清楚tokenizer内部实现方式的同学来说，自己构造prompt时可能注意不到

### Possible Solution2
使用`tokenizer.convert_tokens_to_ids()`而不用`tokenizer.encode()`或者`tokenizer()`，并显式注释提醒，这里我们期望的token就是`['A', 'B', 'C', 'D']`之一，而不是其他组合token

Anyway，感谢你们的工作和奉献！

**Comment by haonan-li** [comment]
感谢提醒，使用`tokenizer.convert_tokens_to_ids()`会更符合我们map到token的期望 ，代码已更新。
