### ISSUE TITLE
Support Qwen-7b

### ISSUE THREAD

**Issue by mMrBun** [haonan-li/CMMLU#16]
Thanks for your work!
I want to do a comparison between chatglm and qwen,Do you plan to support?

**Comment by mMrBun** [comment]
I attempted to evaluate Qwen-7b using hf_causal_model.py, but encountered an error at line 43. The specific reason is that the choice_ids at line 21 are ["None", "None", "None", "None"].
![企业微信截图_16916469205867](https://github.com/haonan-li/CMMLU/assets/52190211/f60ca48a-6446-4b67-a118-2e6b00573319)

**Comment by haonan-li** [comment]
Thank you for reporting the issue. We will check it soon and support Qwen soon.
