### ISSUE TITLE
CMMLU测试

### ISSUE THREAD

**Issue by huayicong23** [haonan-li/CMMLU#27]
您好，Mengzi-7B已邮件测试api，麻烦您抽空测试下，谢谢！

**Comment by huayicong23** [comment]
> 您好，Mengzi-7B已邮件测试api，麻烦您抽空测试下，谢谢！

发送邮箱为nathan.8270.n@gmail.com

**Comment by haonan-li** [comment]
已完成测试并更新。

**Comment by huayicong23** [comment]
> 已完成测试并更新。

收到，辛苦
