### ISSUE TITLE
外部API接口的输入/输出格式和邮箱地址

### ISSUE THREAD

**Issue by jru001** [haonan-li/CMMLU#46]
你好，关于私有模型的外部API接口，有以下问题需要您解答下：
1.  API是一个Model Native的接口吗？即输入任意一个text，输出一个text？
2. 需要我将 few-shot部分包在接口里面吗？
3. 输出的答案如果包含了A，B，C，D以外的部分，删除这多余部分的工作是由我的API自动去除还是你们验证时处理？比如 src 中的部分脚本只取了第一个token是ABCD的置信度，不关心后续多余部分的token。但我的API接口不可能返回给你置信度。
4. 可以提供个邮箱地址，方便我将外部API调用脚本发送至您。

谢谢！

**Comment by haonan-li** [comment]
你好，
关于API，输入（包括fewshot）我们会处理好，您只需要提供您模型对于输入的真实输出就可以。所以对于上面的问题的答案是：
1. 是的
2. 不需要
3. 我们做
4. nathan.8270.n@gmail.com

**Comment by jru001** [comment]
感谢

**Comment by jru001** [comment]
已发送至上述邮箱，辛苦CLLMU团队进行测试，感谢！

**Comment by haonan-li** [comment]
你好，已完成0-shot 的测试，结果如下：

STEM                                     63.93
Humanities                               77.95
Social Science                           76.28
Other                                    72.99
China specific                           72.94
Overall                        72.74

需要继续测试 5-shot的吗？需要在榜单更新吗？

**Comment by jru001** [comment]
您好，感谢你们的测试！需要继续测试5-shot。需要更新榜单，模型名如邮件中所提即可，谢谢。

**Comment by haonan-li** [comment]
已更新
