### ISSUE TITLE
ChatGLM2-6B使用默认参数跑，相比于ChatGLM-6B速度慢5倍以上，不知道是什么原因

### ISSUE THREAD

**Issue by xujunrt** [haonan-li/CMMLU#5]

**Comment by haonan-li** [comment]
对于ChatGLM 我们提供了两个方案：1. 预测下一个token是[A,B,C,D]的概率 对应函数eval()，2. 生成内容并正则匹配答案 对应函数eval_chat()，都是定义在src/chatglm.py 里面。
如果用的是同一个函数，可以再检查两次run的其他不同，比如GPU有没有被其他任务占用之类。
我们这边没有详细的速度对比，但是几小时内可以完成所有subjects的测试。

**Comment by xujunrt** [comment]
> 对于ChatGLM 我们提供了两个方案：1. 预测下一个token是[A,B,C,D]的概率 对应函数eval()，2. 生成内容并正则匹配答案 对应函数eval_chat()，都是定义在src/chatglm.py 里面。 如果用的是同一个函数，可以再检查两次run的其他不同，比如GPU有没有被其他任务占用之类。 我们这边没有详细的速度对比，但是几小时内可以完成所有subjects的测试。

我测试了，用eval函数测试没有问题，用eval chat 速度慢非常多

**Comment by haonan-li** [comment]
> > 对于ChatGLM 我们提供了两个方案：1. 预测下一个token是[A,B,C,D]的概率 对应函数eval()，2. 生成内容并正则匹配答案 对应函数eval_chat()，都是定义在src/chatglm.py 里面。 如果用的是同一个函数，可以再检查两次run的其他不同，比如GPU有没有被其他任务占用之类。 我们这边没有详细的速度对比，但是几小时内可以完成所有subjects的测试。
> 
> 我测试了，用eval函数测试没有问题，用eval chat 速度慢非常多

那可能是生成chat的时候，生成长度较长，所以时间久。
