### ISSUE TITLE
数据集怎么回事

### ISSUE THREAD

**Issue by houxiang676** [haonan-li/CMMLU#62]
from datasets import load_dataset
cmmlu=load_dataset(r"haonan-li/cmmlu", 'agronomy')
print(cmmlu['test'][0])

{'_data_files': [{'filename': 'data-00000-of-00001.arrow'}], '_fingerprint': '8fd80049c30cf62f', '_format_columns': None, '_format_kwargs': {}, '_format_type': None, '_output_all_columns': False, '_split': 'test'}

**Comment by haonan-li** [comment]
你好，我这边没有复现，以下是我的输出。
猜测你这边可能是环境问题。

`⇒  python
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datasets import load_dataset
>>> cmmlu=load_dataset(r"haonan-li/cmmlu", 'agronomy')
Downloading builder script:   0%|                                                                                                                                                                                 | 0.00/4.93k [00:00<?, ?B/s]Downloading builder script: 100%|███████████████████████████████████████████████████████| 4.93k/4.93k [00:00<00:00, 6.47MB/s]
Downloading readme: 100%|███████████████████████████████████████████████████████| 4.87k/4.87k [00:00<00:00, 7.28MB/s]
Downloading and preparing dataset cmmlu/agronomy to /Users/lihaonan/.cache/huggingface/datasets/haonan-li___cmmlu/agronomy/1.0.1/0e7c0fd145d72b4a8ba28e67596cd025c6e18831fb883d3afa38b01468d8eff9...
Downloading data: 100%|███████████████████████████████████████████████████████| 1.08M/1.08M [00:01<00:00, 1.02MB/s]
Dataset cmmlu downloaded and prepared to /Users/lihaonan/.cache/huggingface/datasets/haonan-li___cmmlu/agronomy/1.0.1/0e7c0fd145d72b4a8ba28e67596cd025c6e18831fb883d3afa38b01468d8eff9. Subsequent calls will reuse this data.
100%|███████████████████████████████████████████████████████| 2/2 [00:00<00:00, 205.17it/s]
>>> print(cmmlu['test'][0])
{'Question': '在农业生产中被当作极其重要的劳动对象发挥作用，最主要的不可替代的基本生产资料是', 'A': '农业生产工具', 'B': '土地', 'C': '劳动力', 'D': '资金', 'Answer': 'B'}`
