### ISSUE TITLE
【数据错误】huggingface 上的数据加载有一个错误

### ISSUE THREAD

**Issue by LiuLinyun** [haonan-li/CMMLU#7]
![image](https://github.com/haonan-li/CMMLU/assets/27199777/80675dd7-7897-45b3-ba6d-0a513ee6fbfe)

看csv文件是问题和选项之间少了一个逗号，在世界宗教 world_religions.csv 文件中

**Comment by haonan-li** [comment]
谢谢指出，已修正。
