### ISSUE TITLE
 Areas for improvement

### ISSUE THREAD

**Issue by endNone** [haonan-li/CMMLU#78]
Please allow me to raise two issues in the project. One is that the base model and the fine-tuned model are mixed up on the leaderboard. The other is that the bash scripts are minimally redundant; one script per family of models is sufficient.

**Comment by haonan-li** [comment]
Totally agree with you, we will maintain it when we have time. Thank you for your suggestion, welcome to submit pr if you are happy to help. Thanks.

**Comment by endNone** [comment]
Okay, I will do my best to help improve the large model evaluation in my spare time.
