### ISSUE TITLE
get_results出来的分数有一定随机性

### ISSUE THREAD

**Issue by ztxz16** [haonan-li/CMMLU#8]
测试结果已经输出成csv了，每次调用get_results出来的分数会随机飘动，这个是正常的吗？

**Comment by haonan-li** [comment]
你好，这个是因为在用正则匹配答案时，有一些答案无法被匹配到，于是为了公平对比，我们随机生成ABCD中的一个选项，可以参考[代码](https://github.com/haonan-li/CMMLU/blob/master/src/mp_utils.py#L178)。
我们已经尽可能匹配更多的情况，所以这个波动应该会很小。

**Comment by ztxz16** [comment]
明白了，谢谢
